FROM python:2.7
LABEL maintainer="hkube.dev@gmail.com"
LABEL description="This is a base algorithm for Python 3 env"

ADD requirements.txt /hkube/algorithm-runner/requirements.txt
WORKDIR /hkube/algorithm-runner
RUN pip install -r requirements.txt

COPY . /hkube/algorithm-runner/
CMD ["python", "-u", "app.py"]